<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Voice Bunny</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Voice Bunny</h1>
        <div>integrated with popcorn API</div>
        <form action="send" method="POST">
        <input type="submit" value="<?php if (isset($error)) : ?> Try Again! <?php else : ?> Get a random synopse! <?php endif; ?> ">
        </form>
            <h2><?= htmlspecialchars($text); ?></h2>
            <?php if (isset($error)) : ?>
                <h2 style="color:red;">Damn! <?= htmlspecialchars($error); ?></h2>
            <?php endif; ?>
    </body>
</html>
